---
# tasks file for docke
- name: create image docker
  docker_image:
    name: lcimage:latest
    build:
     path: /var/lib/jenkins/workspace/CD_Project
     pull: no
    source: build
    state: present
    force_source: true
- name: run container docker
  docker_container:
    name: myappcontainer
    image: lcimage:latest
    state: started
    recreate: true
    ports:
     - "4200:80"
